Add support for India Residency
mixpanel/mixpanel-utils pull request #63
Opened 2024-11-05 00:29 UTC by myronkaifung

- Changed `eu` param to `residency`
- `Residency` is a str that accepts 'us', 'eu', or 'in'. Default value = "us"
- Updated readme to reflect the above

2024-11-05 01:14 UTC, austinpray-mixpanel approved these changes

2024-11-05 16:52 UTC, austinpray-mixpanel requested changes
Future proofing discussion happening in slack. Defer to @dongjae93

2024-11-12 17:11 UTC, dongjae93 requested changes

2024-11-12 17:11 UTC, dongjae93 commented on src/mixpanel_utils/__init__.py
> +            else "https://data-in.mixpanel.com/api"
let's follow what Ted suggested and make this future proof. The validation logic ensures we will have valid residency value so we can do something like 
if us:  "https://data.mixpanel.com/api"
else: f"https://data-{residency}.mixpanel.com/api"

2024-11-12 17:11 UTC, dongjae93 commented on src/mixpanel_utils/__init__.py
> +            else "https://api-in.mixpanel.com"
same as above

2024-11-12 17:11 UTC, dongjae93 commented on src/mixpanel_utils/__init__.py
> +            else "https://in.mixpanel.com/api"
same as above

2024-11-14 23:58 UTC, myronkaifung commented
@dongjae93 would you please review again?

2024-11-14 23:59 UTC, dongjae93 approved these changes
LGTM!

2024-11-15 00:02 UTC, myronkaifung commented
Can you merge for me? I have no write access

2024-11-20 18:54 UTC, merged